import type { Metadata } from "next";
import { Roboto, Merriweather } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";
import ScrollTopButton from "@/components/ScrollTopButton";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});
export const metadata: Metadata = {
  title: "Viespacińnik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${merriweather.className}`}>
        <Header />
        <div className="global-wrapper">
          {children}
          <ScrollTopButton />
        </div>
      </body>
    </html>
  );
}
