import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
import ScrollTopButton from "@/components/ScrollTopButton";

export const metadata: Metadata = {
  title: "Viespacińnik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div className="global-wrapper">
          {children}
          <ScrollTopButton />
        </div>
      </body>
    </html>
  );
}
